name: ci/cron-pull

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - ci
  schedule:
    # Every five minutes
    - cron:  '*/5 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
