name: ci/cron-pull

on:
  push:
    branches:
      - ci
  pull_request:
    branches:
      - ci
  schedule:
    # Every five minutes
    - cron:  '*/5 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main

      - name: Pull changes from upstream
        run: |
          git pull https://github.com/llvm/llvm-project.git main:main \
            --rebase --no-tags

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
